### ISSUE TITLE
Improvements to the generator

### ISSUE THREAD

**Issue by angelhodar** [colinhemphill/nextjs-resume#13]
Hi, first of all **congratulations** for this awesome project! I have just deployed it and it has been pretty easy. I have thought about some improvements that could be made to the general workflow and to avoid extra boilerplate:

1. The CMS part seems to be redundant and could be removed as it only adds boilerplate and overhead to the configuration and the code. To solve this I have thought about just having a [Json Resume Schema](https://jsonresume.org/schema/) in a folder that the user fills and extract all the information from there (even though its not as intuitive as a headless CMS), or create markdown templates as you say in #4 from that json data. Another option would be using the **Linkedin API**, because all the information I have added to the CMS is already in my linkedin. Unfortunately it seems that they dont give easy access to experience, interests and skills info about a profile, only basic profile data like email, name and so on. 
2. I have used **Prismic** and it was quite easy to use even though its my first time using a headless CMS. However, it would be easier if you add just some pictures of the contenful and prismic dashboards to map better the info you request with the CMS interface. For example, it took me like 10 minutes (maybe I am just stupid) to realize that the **schema** you mention in the CMS setup is a **type** in the prismic dashboard, and the text type is a *Key Text* element in the type creation.
3. There is some information that could be added, for example **languages**, **volunteer**, **publications**, etc (just based on the *JSON Resume Schema*) . Anyway I suppose you already know it ;)
4. More information for devs about **how the project is structured**, how to modify x section, etc would be a + since for example my knowledge of NextJS, CSS, and so on is still in the Familiar level ;P

What do you think? I reached your repo because I was looking for some templates and ideas to create my own web, here you have some links with beautiful designs and ideas that might help you:

* https://github.com/samuelkraft/samuelkraft-next
* https://github.com/zachweinberg/personal-site
* https://github.com/wirtzdan/website
* https://github.com/grikomsn/griko.id
* https://github.com/timolins/timo-sh
* https://github.com/ShinteiMai/graphql-next-resume

Again, thank you for your time to create this! I think it has the potential to be very popular in the NextJS ecosystem! If you need help just tell me ;)

**Comment by colinhemphill** [comment]
Hi @angelhodar, and thanks for reaching out! I'm glad you enjoyed the experience, and hopefully we will be able to get some improvements underway to make this much more accessible.

As you mentioned, one of my main goals is to implement a simpler method for managing content that doesn't require any external CMS setup, and I would like for this to be the default of the project while still allowing users to integrate with a CMS if they prefer. That might be a JSON schema, markdown templates, or something else. I have looked at JSON Resume Schema quite a bit, and thus far I have tried to stay away from it, primarily because there is already a good Next.js template for it!

https://github.com/jkga/me

I'm also hesitant to expand the flexibility of the template _too_ much. I think there will be a difficulty maintaining a really nice clean look if we allow for too much expansion. While adding new sections would work great on the web version, it would be much more challenging to generate a PDF that still maintains its elegance. I'm personally a fan of the single page résumé, both as an employee and as one who conducts interviews. I think the expectation for what a résumé should contain also varies wildly based on where you live, so it's entirely possible that this is well-suited to the USA but not somewhere else. I would be really interested to know what other employers are looking for in a résumé so that I can tailor the default layout here to better suit more people's needs!

It's also worth noting that this is explicitly _not_ designed to be a personal website, rather a quick link for sending to a potential employer. In the case of my own personal website, the résumé is at a separate subdomain: https://github.com/colinhemphill/colinhemphill-website

**Comment by colinhemphill** [comment]
@angelhodar for what it's worth (I know it's been a very long time), this template has been completely re-written with fully custom styles (no Bootstrap, supports dark mode), a faster and easier to deploy PDF generator, and it defaults to simple Markdown files for content management (with the potential to add headless providers later as plugins).

So now you can literally press the "Deploy" button and you have a resume on Vercel! Then you just have to clone it locally to edit your Markdown.
