### ISSUE TITLE
redeploy caused AWS lambda size limit to be hit

### ISSUE THREAD

**Issue by justin-hackin** [colinhemphill/nextjs-resume#163]
Although I didn't change the lambda function for generating the pdf, editing the pdf template to remove the page break caused Vercel deploy to fail because the lambda exceeded limit size. I can't understand why this would have happened because the bulk of the function is from the `chrome-aws-lambda` dependency and it is pinned in the repo. My only guess is that the limit changed.  There's a [known issue](https://github.com/alixaxel/chrome-aws-lambda/issues/200) with  `chrome-aws-lambda` being too big. Downgrading all the way to `2.1.1` got my deploy under the limit. However, this version doesn't work with the code and clicking the PDF button results in a 500 error on the request with response body `Internal Server Error`.

**Comment by colinhemphill** [comment]
Hey @justin-hackin thanks for the note. Not sure when you started your own resume, but when I went to [v2.0.0](https://github.com/colinhemphill/nextjs-resume/blob/main/CHANGELOG.md#200---2022-02-26) of this project in February I dropped the Puppeteer/AWS Lambda dependencies for this very reason. The new version now generates the PDF client-side.

Running Puppeteer on Vercel within its own project generally works fine, but something about pairing it with the Next API structure often causes it to break the 50 MB limit. You may have some luck if you reorganize the project to put the api folder at the project root: https://github.com/vercel/vercel/issues/4739

I'm going to close this since I'm not working on v1 anymore, but I realize v2 is quite a bit different and not something you can easily migrate to.
