### ISSUE TITLE
Unordered links in professional experience overflow page

### ISSUE THREAD

**Issue by justin-hackin** [colinhemphill/nextjs-resume#205]
<img width="735" alt="Screen Shot 2023-02-09 at 3 38 45 PM" src="https://user-images.githubusercontent.com/4888331/217936130-6f9f7e92-a869-4c83-a61a-b424f34ebd3a.png">

Could be related to [this issue](https://github.com/diegomura/react-pdf/issues/2182)

**Comment by justin-hackin** [comment]
There's a workaround [here](https://github.com/danomatic/react-pdf-html/issues/50)

**Comment by colinhemphill** [comment]
@justin-hackin Thanks for looking into this! I'm working on trying to make some substantial PDF improvements in #213 which includes your renderer function for lists. The [demo PDF](https://nextjs-resume-mjo1rbe7x-colin-hemphill.vercel.app/api/pdf) now includes some changes to showcase the changes:

- An unordered list
- Emojis
- SVG icons instead of rasters

Would appreciate some feedback on that PR if you have time to give it a look!

**Comment by colinhemphill** [comment]
This has been fixed in 3.1.0!

**Comment by justin-hackin** [comment]
> @justin-hackin Thanks for looking into this! I'm working on trying to make some substantial PDF improvements in #213 which includes your renderer function for lists. The [demo PDF](https://nextjs-resume-mjo1rbe7x-colin-hemphill.vercel.app/api/pdf) now includes some changes to showcase the changes:
> 
> * An unordered list
> * Emojis
> * SVG icons instead of rasters
> 
> Would appreciate some feedback on that PR if you have time to give it a look!

Sorry I missed the call for review here, glad you found a fix
